// v:
var noskimproducts = true;
var skimwords_hover_name = 'neutral';
var skimwords_horizontal_distance = 200;
var skimwords_vertical_distance = 300;
var nounlinked = true;
var skimlinks_audience_optout = true;
var skimlinks_cookie_sync_optout = true;
if (typeof skimlinks_exclude === "undefined") {
var skimlinks_exclude = ['*.buzzfeed.com','joyus.com','amazon.com.mx','amazon.de','amazon.in','amazon.co.uk','amazon.com','gettyimages.com'];
}
if (typeof skimlinks_site === "undefined") {
var skimlinks_site = 'buzzfeed.com';
}
var skimlinks_replace_timeout = 300;
var skimwords_instant = true;
if (typeof noskimwords === "undefined") {
var noskimwords = true;
}
var noskoupon = true;
var skimlinks_pub_id = '74679X1524629';

(function(g){var ib,jb,P,Q,kb,lb,mb,nb,l,T,Aa,ea,Ba,Ca,Da,fa,ob,pb,qb,rb,Ea,i,p,ga,ha,Fa,Ga,m,s,U,v,R,ia,G,ja,sb,H,V,W,Ha,q,Ia,Ja,ka,tb,e,la,ub,vb,ma,na,Ka,wb,oa,X,xb,yb,La,zb,Y,Ab,pa,Ma,Na,Bb,Oa,Pa,Cb,Db,Eb,Fb,Gb,Qa,Hb,Ib,I,Jb,Kb,t,Lb,Ra,Mb,Sa,Nb,Ta,Ob,Pb,Qb,Rb,qa,Sb,Tb,Ua,Va,Wa,Xa,Ya,Ub,A,Vb,Za,$a,ra,sa,ta,ab,w,Z,bb,J,cb,$,db,ua,K,aa,S,va,B,wa,x,y,Wb,C,Xb,Yb,Zb,ba,eb,fb,L,n,o,D,xa,ca,r,u,E,$b,z,M,N={}.hasOwnProperty,da=[].indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(b in this&&this[b]===
a)return b;return-1};G=ja=null;"undefined"!==typeof skimlinks_context_window&&null!==skimlinks_context_window&&(g=g[skimlinks_context_window]);i=g.document;sb=/http:/g;s=function(){return function(){var a;a=navigator.userAgent.toLowerCase();a=/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version)?[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||0>a.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(a)||[];return{browser:a[1]||"",version:parseFloat(a[2])||0}}}(this)();q={};Ja=(new Date).getTime();
ka={"t.umblr.com":{name:"z"}};H=v=null;Ia=ia=!1;V=[];R=[];W=[];U={domains:[]};m={};Ha=[];K=y=null;w="";wa=B=aa=Z=null;sa=[];$=[];J=va=ra=ta=null;S=x=!1;ua=300;ab=db=cb=Za=$a=!1;ca=xa=r=null;E=u=n="";D=o=0;L=[];fb=!0;z=g.location;M="";Ta=Q=!1;ha=[];ib=["noskim","norewrite"];jb="*.g.doubleclick.net,*mjxads.internet.com,*pgpartner.co.uk,*pgpartner.com,*pricegrabber.co.uk,*pricegrabber.com,*overture.com,*youtube.com,paid.outbrain.com,trc.taboola.com,traffic.outbrain.com,zergnet.com,*.criteo.com,track.celtra.com".split(",");
bb=function(){return!0};P=[];la=function(a){var b;b=i.createElement("a");b.href=a;return C(b.hostname)};Sb=function(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)};tb=function(){var a,b;a="";for(b=0;8>b;++b)a+=Sb();return a};e=function(){return function(a,b){return null!=g[a]?g[a]:null!=window[a]?window[a]:b}}(this);mb=function(){var a;E=tb();ja=null!=(a=i.getElementsByTagName("html"))?a[0]:void 0;V=e("skimlinks_included_classes",[]);R=e("skimlinks_excluded_classes",[]);W=
e("skimlinks_included_ids",[]);G=e("force_location")?la(e("force_location")):z.hostname;y=e("skimlinks_tracking",!1);y=e("affiliate_tracking",y);K=e("skimlinks_site")||e("skimlinks_sitename")||!1;w=e("skimlinks_domain")?"http://"+e("skimlinks_domain"):"";Z=e("skimlinks_google",!1);aa=null!=Z?Z:"skimout";B=e("skimlinks_target",!1);wa=e("sl_test",!1);e("skimlinks_cookie_sync",[]);sa=e("skimlinks_exclude",[]);$=e("skimlinks_include",[]);e("skimlinks_noright",!1);ta=e("skimlinks_exrel",!1);ra=e("skimlinks_byrel",
!1);Za=e("skimlinks_add_nofollow",!1);va=e("skimlinks_blocked_tag",!1);db=e("skimlinks_profiling",!1);S=e("skimlinks_strip_attribute",!1);e("skimlinks_ad_images",!1);"number"===typeof e("skimlinks_replace_timeout")&&(ua=e("skimlinks_replace_timeout"));"boolean"===typeof e("skimlinks_before_click_handler")&&($a=e("skimlinks_before_click_handler"));J=0;x=yb();cb=e("skimlinks_ignore_hidden_links",!1);ab=e("skimlinks_first_party_na",!1);Ta=e("skimlinks_url_extraction_rules",!1);ha=e("skimlinks_extra_redir_params",
[]).join("&");r=e("skimlinks_pub_id","");Ha=e("skimlinks_link_impression_exclude_selector",[]).join(", ");o=e("skimlinks_dnt",0);D=e("skimlinks_nocookie",!1);xa=e("noimpressions",!1);ca=e("noskimlinks",!1)||e("noskim",!1)||!1;fb=e("skimlinks_affiliate_unknown_links",!0);ca&&(F.skimlinks=!1);F.skimwords=!1;F.unlinked=!1;if(g.document&&g.document.referrer)M=g.document.referrer;Hb(G)&&(ca=!0);y&&!/^[a-z0-9_\\|]+$/i.test(y)&&(y=!1);R.push("noskimlinks");R.push("noskim");i.createTextNode("");return!0};
$b=function(a,b){return a.hasOwnProperty(b)};yb=function(){var a;return"function"===typeof(a=new Date).getTimezoneOffset?a.getTimezoneOffset():void 0};Hb=function(a){var b,c,d,f;if(c=e("noskim_domains",!1))for(d=0,f=c.length;d<f;d++)if(b=c[d],-1!==a.toLowerCase().indexOf(b.toLowerCase()))return!0;return!1};C=function(){return function(){var a;a=/^www\./i;return function(b){return b.replace(a,"")}}}(this)();T=function(){return function(){return i.addEventListener?function(a,b,c,d){null==d&&(d=!1);
if(a&&(a.nodeName||a===g))return a.addEventListener(b,c,d)}:function(a,b,c){if(a&&(a.nodeName||a===g))return a.attachEvent("on"+b,function(){return 7>s.version&&!g.event?(setTimeout(function(){return c.call(a,g.event)},100),!0):c.call(a,g.event)})}}}(this)();(function(){return function(){return i.createElement("div").getElementsByClassName?function(a,b){return Y(a,b)?a:a.getElementsByClassName(b)}:function(a,b){var c;c=Da(b);return Fa(a,c)}}})(this)();p=function(){return function(){var a,b;b=[function(){var b,
d,f,k;f=[["%20","+"],["!","%21"],["'","%27"],["\\(","%28"],["\\)","%29"],["\\*","%2A"],["\\~","%7E"]];k=[];for(b=0,d=f.length;b<d;b++)a=f[b],k.push([RegExp(a[0],"g"),a[1]]);return k}()];return function(c){var d,f,c=encodeURIComponent(c);for(d=0,f=b.length;d<f;d++)a=b[d],c=c.replace(a[0],a[1]);return c}}}(this)();Pa=function(){return function(){var a;a=/^\/\/|https?:\/\//i;return function(b,c){return a.test(b)&&(!c||!G||-1===c.indexOf(G))&&(!G||-1===G.indexOf("."+c))}}}(this)();l=function(a,b,c){var d;
3<=arguments.length&&("undefined"!==typeof a.setAttribute?a.setAttribute(b,c):a[b]=c);try{return d=a[b],null==d&&(d=a.getAttribute(b)),d}catch(f){return null}};ob=function(a,b,c){arguments[1]="data-"+b;return l.apply(this,arguments)};Yb=function(a,b){var c;c=a.innerText||a.textContent||a.nodeValue;if(2<=arguments.length)"undefined"!==typeof a.innerText?a.innerText=b:a.textContent=b,c=b;return c};ba=function(){return function(){var a,b;if(String.prototype.trim)return function(a){return null===a?"":
String.prototype.trim.call(a)};a=/^\s+/;b=/\s+$/;/\S/.test("\u00a0")&&(a=/^[\s\xA0]+/,b=/[\s\xA0]+$/);return function(c){return null===c?"":c.toString().replace(a,"").replace(b,"")}}}(this)();Lb=function(a){var b,c,d,f,k;if("object"===typeof a||a instanceof Array){f="";d=0;c=a instanceof Array;for(k in a)N.call(a,k)&&(b=a[k],0<d&&(f+=","),c?f+=t(b):(b=t(b),f+='"'+k+'":'+b),d++);return c?"["+f+"]":"{"+f+"}"}return"string"===typeof a?(b=a.replace(/"/g,'\\"',a),'"'+b+'"'):isNaN(a)?"null":a.toString()};
t=function(){return function(){var a;return"undefined"!==typeof JSON&&null!==JSON&&JSON.stringify&&'["la"]'===JSON.stringify(["la"])?(a=JSON.stringify,function(b){return a(b)}):Lb}}(this)();ga=function(){return function(){var a,b;a=/[-[\]{}()*+?.,\\^$|#\s]/g;b=/\s+/g;return function(c){return c.replace(a,"\\$&").replace(b,"s+")}}}(this)();qa={topics:{},on:function(a,b){var c;if(null==(c=this.topics)[a])c[a]=[];return this.topics[a].push(b)},off:function(a,b){var c;c=0<=da.call(this.topics[a],b);if(-1<
c)return this.topics[a].splice(c,1)},once:function(a,b){var c;c=function(a){return function(){c.called||b.apply(a,arguments);return c.called=!0}}(this);c.called=!1;return this.on(a,c)},publish:function(a,b){var c,d,f,k,e,g;c={topic:a,extra:b};if(this.topics[a]){e=this.topics[a];g=[];for(f=0,k=e.length;f<k;f++)d=e[f],g.push("function"===typeof d?d(c):void 0);return g}}};Da=function(a){a=ga(a);return RegExp("\\b"+a+"\\b","i")};Y=function(a,b){return a.className?Da(b).test(a.className):!1};Fa=function(a,
b){var c,d,f,k,e;d=[];a.className&&b.test(a.className)&&d.push(a);e=a.childNodes;for(f=0,k=e.length;f<k;f++)c=e[f],d=d.concat(Fa(c,b));return d};Ib=function(a){for(var b,c,d,f;a&&a!==ja;){c=a.id;for(d=0,f=V.length;d<f;d++)if(b=V[d],Y(a,b))return!1;for(d=0,f=W.length;d<f;d++)if(b=W[d],c===b)return!1;for(c=0,d=R.length;c<d;c++)if(b=R[c],Y(a,b))return!0;a=a.parentNode}return V.length||W.length?!0:!1};Na=function(a,b,c){null==c&&(c=!1);for(b=RegExp("\\b(?:(?:"+ga(b)+")|(?:noskim))\\b","i");null!=a&&a!==
ja;){if(a.className&&b.test(a.className))return!0;a=c?null:a.parentNode}return!1};La=function(a){return ob(a,"skimlinks-tracking")||y};Ba=function(a,b){var c,d,f,k,g;r||(r=e("skimlinks_pub_id",""));g=La(a);k=M?"&pref="+p(M):"";c=!1;0<b.indexOf("#slm-")&&(d=b.split("#slm-"),2===d.length&&!isNaN(d[1])&&10*parseInt(d[1])===10*d[1]&&(b=d[0],c=d[1]));f=l(a,"data-skimlinks-editor")&&1===parseInt(l(a,"data-skimlinks-editor"))?1:0;w||(w=e("skimlinks_domain")?"http://"+e("skimlinks_domain"):fa());Na(a,"noskimlinks")||
(d=l(a,"data-skim-creative"),b=""+w+"/?id="+r+""+(K?"&site="+K:"")+""+(wa?"&test="+wa:"")+""+(g?"&xcust="+g:"")+""+(!1!==c?"&xs=9":"&xs=1")+"&isjs=1&url="+p(b)+"&xguid="+n+"&xuuid="+E+"&xsessid="+u+"&xcreo="+(a&&null!=d?d:0)+"&xed="+f+"&sref="+p(z)+""+k+""+(o?"&dnt="+o:"")+""+(D?"&fdnt=1":"")+""+(!1!==c?"&slmcid="+c:"")+""+(!1!==x?"&xtz="+x:""));0<ha.length&&(b+="&"+ha);Q&&!Na(a,"noskimlinks")&&(b+="&abp=1");return b};ma=function(a){var b,c,a=a.target||a.srcElement;b=null!=a?null!=(c=a.nodeName)?
"function"===typeof c.toUpperCase?c.toUpperCase():void 0:void 0:void 0;"A"!==b&&"AREA"!==b&&(a=oa(a));return a};Va=function(a){var b;b=ma(a);if(!b)return!0;Tb(b);if(e("vglnk")&&Y(b,"skimwords-link"))a&&a.stopPropagation?a.stopPropagation():(a=g.event,a.cancelBubble=!0);return!0};oa=function(a){for(;a.parentNode;)if(a=a.parentNode,"A"===(null!=a?a.nodeName.toUpperCase():void 0)||"AREA"===(null!=a?a.nodeName.toUpperCase():void 0))return a;return null};Xb=function(a){return a=n?a.replace(/([&\?]{1})xguid=([a-fA-F0-9]{32})/,
"$1xguid="+n):a.replace(/([&\?]{1}xguid=[a-fA-F0-9]{32})/,"")};Ca=function(a,b){var c,d;d=a();if(null!=d)return function(a){return a(d)};c=null;qa.once(b,function(){return"function"===typeof c?c(a()):void 0});return function(a){return c=a}};ub=function(){var a;return null!=(a=P[0])?a.guid:void 0};Ca(function(){var a;return null!=(a=P[0])?a.csp:void 0},"beacon");Ca(function(){var a;return null!=(a=P[0])?a.ts:void 0},"beacon");Tb=function(a){var b,c,d,f;d=!1;b=Z;a&&a.nodeName&&"A"!==a.nodeName.toUpperCase()&&
"AREA"!==a.nodeName.toUpperCase()&&(a=oa(a));if(a){f=vb(a);w||(w=e("skimlinks_domain")?"http://"+e("skimlinks_domain"):fa());c=w;if(f.length>=c.length&&f.substr(0,c.length)===c)return!0;if("msie"===s.browser&&a.childNodes.length&&3===a.childNodes[0].nodeType)d=a.innerHTML;c=-1!==f.indexOf(c)?f:Ba(a,f);b&&ac(f);Ua(a);a.href=c;a.href=c;d&&a.innerHTML!==d&&setTimeout(function(){return function(){return a.innerHTML=d}}(this),ua)}return!0};fa=function(){var a;a="msie"===s.browser&&8>=s.version;return!ub()&&
!a?"//go.skimresources.com":"//go.redirectingat.com"};I=function(a){return-1!==(w||fa()).indexOf(a)||-1!==a.indexOf("go.redirectingat.com")||-1!==a.indexOf("go.skimresources.com")};Bb=function(a){return!0===m[a]||(null===m[a]||void 0===m[a])&&fb&&!I(a)};Qa=function(a){return Bb(a)};Nb=function(a){return a in ka};Jb=function(a){var b,c;if(!va)return!1;b=null!=a?a.previousSibling:void 0;if(!b)return!1;a=("["+va+"]").toLowerCase();c=Yb(b);if(!c)return!1;c=c.toLowerCase();c=ba(c);b=c.lastIndexOf(a);return-1!==
b&&b+a.length===c.length};Ma=function(a){return!a||ra&&a===ra||!Ab(a)};Ab=function(a){var b,c,d,f;if(!a)return!1;b=a.toLowerCase().split(/\s+/);a=ta?[ta.toLowerCase()]:[];a=a.concat(ib);for(d=0,f=b.length;d<f;d++)if(c=b[d],0<=da.call(a,c))return!0;return!1};Aa=function(){var a,b,c,d;v={};H={};K&&sa.push(K);d=sa.concat(jb);for(b=0,c=d.length;b<c;b++)a=d[b],v[a]=a.length;for(b=0,c=$.length;b<c;b++)a=$[b],H[a]=a.length;return v};Oa=function(a){var b,c,d;(null===v||null===H)&&Aa();if(!a)return!1;for(b in v)if(N.call(v,
b))if(c=v[b],0===b.indexOf("*")){if(b=b.substr(1),c-=1,d=a.lastIndexOf(b),-1!==d&&d===a.length-c)return!0}else if(a===b)return!0;return!1};Db=function(a){var b,c,d;(null===v||null===H)&&Aa();if(!a)return!1;if(0===$.length)return!0;for(b in H)if(N.call(H,b))if(c="*"===b.substr(0,1),d="*"===b.substr(b.length-1,1),b=b.replace(/\*/g,""),c&&d){if(-1!==a.indexOf(b))return!0}else if(c){if(-1!==a.indexOf(b)&&a.indexOf(b)===a.length-b.length)return!0}else if(d){if(0===a.indexOf(b))return!0}else if(a===b)return!0;
return!1};pa=function(a,b){return Pa(a,b)&&!Oa(b)&&Db(b)};Gb=function(a,b,c){return"selector_bl"===b?Fb(a,c):!1};Fb=function(a,b){return!a&&!b?!1:Boolean(b&&("function"===typeof a.closest?a.closest(b):void 0))};lb=function(a,b){var c,d,f;d=[];for(c in a)N.call(a,c)&&(f=a[c],"data"!==c&&d.push(""+c+"="+f));a.data&&d.push("data="+a.data);return b+"?"+d.join("&")};Zb=function(a,b){var c,d;c=la(b);if(I(c))return!0;c="";0<b.indexOf("#slm-")&&(d=b.split("#slm-"),2===d.length&&!isNaN(d[1])&&10*parseInt(d[1])===
10*d[1]&&(b=d[0],c=d[1]));d=La(a);c={call:"track",data:p('{"pubcode":"'+r+'", "referrer":"'+z+'", "pref":"'+M+'", "site":"'+K+'", "url":"'+b+'", "custom":"'+(d||"")+'", "xtz":'+x+', "uuid":"'+E+'", "slmcid":"'+c+'", "product":"1"}')};o&&(c.dnt=o);D&&(c.fdnt=1);c=lb(c,"//t.skimresources.com/api/");c=c+"&rnd="+Math.random();Ka(c);return!0};Ua=function(a){var b,c;if(!(null!==a&&a.sl_href_restore_scheduled))return b=a.href,c="msie"===s.browser&&7>s.version?1E4:ua,a.sl_href_restore_scheduled=!0,setTimeout(function(){return function(){a.href=
b;a.href=b;return delete a.sl_href_restore_scheduled}}(this),c)};zb=function(a,b){var c,d;d=!1;c=Xb(b);if(c!==b&&(a&&a.nodeName&&"A"!==a.nodeName.toUpperCase()&&"AREA"!==a.nodeName.toUpperCase()&&(a=oa(a)),a)){if("msie"===s.browser&&a.childNodes.length&&3===a.childNodes[0].nodeType)d=a.innerHTML;Ua(a);a.href=c;a.href=c;d&&a.innerHTML!==d&&setTimeout(function(){return function(){return a.innerHTML=d}}(this),300)}return c};Wa=function(a,b){var c,d;Wb(a);B&&l(a,"target",B);d=l(a,"onclick");c="click"===
b.type||"contextmenu"===b.type;if(null!=d&&-1!==d.toString().indexOf("return false")){if(c)return bb(a),Pb(b)}else return bb(a),Va(b)};Ob=function(a){var b,c,d;b=ma(a);d=b.href;c=la(d);I(c)&&(d=zb(b,d));""===n&&ab?Wa(b,a):Zb(b,d);return!0};Ka=function(a){var b,c;b=i.getElementsByTagName("body")[0];c=i.createElement("img");c.src=a;c.width=1;c.height=1;if("undefined"!==typeof c.style)c.style.display="none";b.appendChild(c);return c};X=function(a,b,c,d,f){var O;var k,e,g,j,h;null==c&&(c={});k=c.charset||
null;h=c.target||null;O=null!=(e=c.async)?e:!0,c=O;e=null!=h&&h.document?h.document:i;g=e.getElementsByTagName("head")[0];j=e.createElement("script");j.type="text/javascript";if(k)j.charset=k;if(b)j.onload=j.onreadystatechange=function(a){return function(){var c;c=!1;return function(){var d;d=a.readyState;if(!c&&(!d||"complete"===d||"loaded"===d))return j.onload=j.onreadystatechange=null,c=!0,b.call(h),!0}}}(this)();j.onerror=function(){if(null!=d)return null!=f?d(f):d(!1)};j.async=!1!==c;j.src=a;
g.appendChild(j);return j};na=function(a,b){var c,d,f,e,g,h;f=null;a&&(f=RegExp("\\b"+ga(a)+"\\b","i"));h=[];b||(b=i);d=b.getElementsByTagName("a");for(e=0,g=d.length;e<g;e++){c=d[e];try{c.href&&(!f||c.className&&f.test(c.className))&&h.push(c)}catch(j){}}d=b.getElementsByTagName("area");for(e=0,g=d.length;e<g;e++){c=d[e];try{c.href&&(!f||c.className&&f.test(c.className))&&h.push(c)}catch(l){}}return h};Eb=function(a){return-1!==a.indexOf("itunes.apple.com")||-1!==a.indexOf("itunes.com")||-1!==a.indexOf("phobos.apple.com")?
!0:!1};Wb=function(a){var b,c,d;if(!S)return!1;for(c in S)if($b(S,c)&&(d=S[c],(b=l(a,c))&&0===b.indexOf(d)))b=b.substr(d.length),l(a,c,b);return!0};kb=function(a){var b,c;c=l(a,"rel");b=C(a.hostname);if(!c&&b&&!0===m[b])return l(a,"rel","nofollow")};Pb=function(a){var b;b=ma(a);if(e("_mugicPopWin"))return e("_mugicPopWin")(b);Va(a);return(B?g.open(b.href):g.open(b.href,B)).focus()};Ya=function(a){var b,c,d,f;g.skimlinks_requests_in_flight-=1;a=null!=a?a:{};arguments.length&&(P.push(a),qa.publish("beacon",
a));null!=g.skimlinks_runner&&(g.skimlinks_runner.skimlinks=1);a.guid&&""===n&&(n=a.guid);a.sessid&&""===u&&(u=a.sessid);f=a.merchant_domains||[];for(c=0,d=f.length;c<d;c++)b=f[c],I(b)||(m[b]=!0);for(b in m)null===m[b]&&(m[b]=!1);n&&db&&Rb();if(Za){f=na();for(c=0,d=f.length;c<d;c++)b=f[c],kb(b)}return!0};Rb=function(){var a;a=r.toUpperCase().split("X");if(2===a.length)return a="http://odpp.skimapis.com/"+a[1]+"/profile/"+n+"?callback=skimlinksODPCallback",X(a,!1,{})};Qb=function(a){var b,c,d,f;if(a.status&&
"OK"===a.status&&a.actions&&a.actions.length){d=a.actions;f=[];for(b=0,c=d.length;b<c;b++)a=d[b],"pixel"===a.action?f.push(Ka(a.url)):f.push(void 0);return f}};Ub=function(a){var b,c,d,f;g.skimlinks_requests_in_flight-=1;a=null!=a?a:{};arguments.length&&(P.push(a),qa.publish("beacon",a));null!=g.skimlinks_runner&&(g.skimlinks_runner.skimlinks=1);a.guid&&""===n&&(n=a.guid);a.sessid&&""===u&&(u=a.sessid);f=a.merchant_domains||[];for(c=0,d=f.length;c<d;c++)b=f[c],I(b)||(m[b]=!0);for(b in m)null===m[b]&&
(m[b]=!1);return Ea()};xb=function(a){return-1!==a.indexOf("#slm-")&&(a=a.split("#slm-"),2===a.length&&!isNaN(a[1])&&10*parseInt(a[1])===10*a[1])?parseInt(a[1]):null};Ea=function(a){var b,c,d,f,e,h,O,j;a||(a=0);if(g.skimlinks_requests_in_flight&&5>a)setTimeout(function(){return Ea(a+1)},400*a);else{f=na();c=0;for(O=0,j=f.length;O<j;O++)if(b=f[O],h=ba(b.href),d=C(b.hostname),e=l(b,"class"),(!e||!(-1!==e.indexOf("skimwords-link")||-1!==e.indexOf("skimlinks-unlinked")))&&pa(h,d)&&!Gb(b,"selector_bl",
Ha))if(b=xb(h),Qa(d)?(c++,q.hasOwnProperty(h)?q[h].ae=1:q[h]={count:0,ae:1}):q.hasOwnProperty(h)||(q[h]={count:0,ae:0}),q[h].count++,b)q[h].slmcid=b,0>da.call(L,b)&&L.push(b);J=c;!Ia&&"undefined"!==typeof ya&&null!==ya&&null!=U&&null!=U.domains&&(Ia=!0,ya(U.domains));Vb()}return!0};Vb=function(){"undefined"!==typeof za&&null!==za&&za("skimlinks");return!0};Ga=function(){var a,b,c,d,f,e,g;d=na();c=[];for(e=0,g=d.length;e<g;e++)a=d[e],b=C(a.hostname),f=ba(a.href),a=l(a,"rel"),b&&pa(f,b)&&Ma(a)&&!I(b)&&
void 0===m[b]&&(c.push(b),U.domains.push(b),m[b]=null);return c};nb=function(a,b,c){if(a){$a&&T(a,"mouseup",b,c);T(a,"click",b,c);try{return"onauxclick"in i.createElement("body")?T(a,"auxclick",b,c):T(a,"contextmenu",b,c),!0}catch(d){}}return!1};eb=function(a,b,c){if(0===b)return c;try{return a()}catch(d){return eb(a,b-1,c)}};wb=function(a){if(null==a)return null;for(;"A"!==a.nodeName.toUpperCase();)if(a=eb(function(){return a.parentNode},3,null),null==a)return null;return a};vb=function(a){var b,
c;return Ta&&(b=C(a.hostname),b in ka)?(b="[&?]"+ka[b].name+"=(http[^&]+)",decodeURIComponent(null!=(c=a.href)?c.match(RegExp(b)).pop():void 0)||a.href):a.href};Kb=function(a){return!a||!a.href||0!==a.href.indexOf("http://")&&0!==a.href.indexOf("https://")&&0!==a.href.indexOf("//")?!1:!0};Cb=function(a){if(!cb)return!1;if(null===a.offsetParent||"function"===typeof g.getComputedStyle&&(a=g.getComputedStyle(a),"hidden"===a.visibility))return!0;return!1};pb=function(a){var b,c,d,f;if(g.event)a=g.event;
b=a.originalTarget||a.srcElement||a.target;c=null!=b?b.nodeName.toUpperCase():void 0;"A"!==c&&"AREA"!==c&&(b=wb(b));if(!b||Ib(b)||!Ma(l(b,"rel"))||Jb(b))return!0;f=ba(b.href);c=C(b.hostname);d="click"===a.type||"contextmenu"===a.type;if(Kb(b)&&pa(b.href,c)&&!Cb(b)){b.sl_hidden_domain&&(c=C(b.sl_hidden_domain));if(Qa(c)||Eb(f)||Nb(c))Wa(b,a);else if(d&&Pa(f,c)&&!Oa(c))return B&&l(b,"target",B),Ob(a);return!0}};Mb=function(a,b){var c,d,f,e,h,O;null==b&&(b="skimlinksApplyHandlers");g.skimlinks_requests_in_flight=
(null!=(c=g.skimlinks_requests_in_flight)?c:0)+1;if(!(null!=a&&a.length))return g[b](),!1;c=p('{"pubcode":"'+r+'","domains":_DOMAIN_LIST_,"page":"'+z.href+'"}');e="//r.skimresources.com/api/?callback="+b+(o?"&dnt="+o:"")+(D?"&fdnt=1":"")+"&data="+c;c="msie"===s.browser?2E3:8E3;f=[];for(h=0,O=a.length;h<O;h++)d=a[h],f.push(d),e.replace("_DOMAIN_LIST_",p(t(f))).length>c&&(f=f.slice(0,-1));e=e.replace("_DOMAIN_LIST_",p(t(f)));return X(e,!1,{})};ea=function(a){var b,c;b=[];for(c in a)a.hasOwnProperty(c)&&
b.push(""+c+"="+p(a[c]));return b.join("&")};Ra=function(a,b,c){var d,f,e;if("msie"!==s.browser)f=!1,e=new XMLHttpRequest,e.open("POST",a,!0),e.setRequestHeader("Content-type","application/x-www-form-urlencoded"),0<=da.call(e,"withCredentials")&&(e.withCredentials=!0),e.async="true",e.onreadystatechange=function(){var a,b;if(f)return!0;if(4===e.readyState){f=!0;if(200===e.status){a={};b=e.responseText;if(0===b.indexOf("//"))return c(a),!0;if("undefined"!==typeof JSON&&null!==JSON&&JSON.parse)try{a=
JSON.parse(e.responseText)}catch(d){}c(a);return!0}return!1}},e.send(b);else if(g.XDomainRequest){if(d=new XDomainRequest,0<=da.call(d,"withCredentials")&&(d.withCredentials=!0),d){d.open("POST",a,!0);d.onload=function(){var a;a={};if(0===d.responseText.indexOf("//"))return c(a),!0;if("undefined"!==typeof JSON&&null!==JSON&&JSON.parse)try{a=JSON.parse(d.responseText)}catch(b){}c(a);return!0};d.onerror=function(){return!1};d.onprogress=function(){return!1};d.ontimeout=function(){return!1};d.async=
!0;try{d.send(b)}catch(h){return!1}}}else return!1;return!0};Sa=function(a,b){var c;c={data:t({pubcode:r,domains:a,page:z.href})};ea(c);Mb(a,b);return!0};A=function(){return rb()};qb=function(){var a;g.skimlinksInitialized=!0;if(!ca)return a=Ga(),Sa(a),nb(i,pb,!0)};rb=function(){if(ia)return!1;ia=!0;return Sa(Ga(),"skimlinksApplySecondaryHandlers")};Xa=function(){return function(){return function(){var a,b,c;if(g.skimInitAlreadyCalled)return!1;g.skimInitAlreadyCalled=!0;mb();ec.detect(function(a){return Q=
a});qb();b=function(){if(ia)return!0;try{i.documentElement.doScroll("left")}catch(a){return setTimeout(b,50),!1}return A()};a=function(){return function(){return i.addEventListener?function(){i.removeEventListener("DOMContentLoaded",a,!1);A();return!0}:i.attachEvent?function(){i.detachEvent("onreadystatechange",a);A();return!0}:function(){A();return!0}}}(this)();if("complete"===i.readyState)setTimeout(A,1);else if(i.addEventListener)i.addEventListener("DOMContentLoaded",a,!1),g.addEventListener("load",
A,!1);else if(i.attachEvent){i.attachEvent("onreadystatechange",a);g.attachEvent("onload",A);c=!1;try{c=null===g.frameElement}catch(d){}i.documentElement.doScroll&&c&&b()}return!0}}}(this)();null==g.skimlinksApplyHandlers&&(g.skimlinksApplyHandlers=Ya);null==g.skimlinksApplySecondaryHandlers&&(g.skimlinksApplySecondaryHandlers=Ub);null==g.skimlinksApplyHandlersAlt&&(g.skimlinksApplyHandlersAlt=Ya);null==g.skimlinksODPCallback&&(g.skimlinksODPCallback=Qb);null==g.skimlinksRewriteUrl&&(g.skimlinksRewriteUrl=
Ba);if(null==g.skim_init)g.skim_init=Xa;var bc,h,F,gb,cc,dc,ac,za,ya,hb,N={}.hasOwnProperty;h={pag:"",phr:[],unl:[],pub:"",slc:0,swc:0,ulc:0,jsl:0,jsf:"",guid:"",uuid:"",sessid:"",uc:"",t:1,slmcid:!1};F={skimlinks:!0,skimwords:!0,unlinked:!0};gb=!1;cc=function(){var a,b,c,d,f,e;a=8E3;"msie"===s.browser&&(a=2E3);d={};d.guid=n;d.uuid=E;d.sessid=u;d.pub=r;d.pag=z.href;d.tz=x;d.slmcid=L;d.dl={};d.typ="l";d.hae=J?1:0;c="//t.skimresources.com/api/link?data=";e=0;for(f in q)N.call(q,f)&&(b=q[f],e++,d.dl[f]=
b,b=c+p(t(d)),b.length>a&&(e--,delete d.dl[f]));e&&(c+=p(t(d)),X(c,!1,{async:!0}));return!0};ya=function(){var a;if(xa)return!1;a={};a.guid=n;a.uuid=E;a.sessid=u;a.pub=r;a.pag=z.href;a.dl=q;a.tz=x;a.slmcid=L;a.typ="l";a.hae=J?1:0;a={data:t(a)};o&&(a.dnt=o);D&&(a.fdnt=1);a=ea(a);if(Q||!Ra("//t.skimresources.com/api/link",a,hb))return cc()};ac=function(a){var b,c,d;b=e("pageTracker");d=e("urchinTracker");c="/"+aa+"/"+a;if(null!=b&&b._trackPageview)return b._trackPageview(c),!0;if(d)return d(c),!0;e("_gaq")?
(b=e("_gaq"),b.push(["_trackEvent",aa,"click",a])):e("ga")&&e("ga")("send","event","click",aa,a);return!1};hb=function(){return!0};za=function(a){var b,c;if(xa||gb)return!1;F[a]=!1;a=!0;for(b in F)if(N.call(F,b)&&(c=F[b],!0===c)){a=!1;break}if(a)return gb=!0,bc()};dc=function(){var a;a=(new Date).getTime()-Ja;h.tz=x;h.slc=J;h.swc="undefined"!==typeof sw_handlers&&null!==sw_handlers?sw_handlers:0;h.ulc=0;h.jsl=a;h.guid=n;h.slmcid=L;h.uuid=E;h.sessid=u;h.pref=M;h.phr={};h.unl={};a="//t.skimresources.com/api/track.php?";
o&&(a=a+"dnt="+o+"&");D&&(a+="fdnt=1&");Q&&(a+="abp=1&");a=a+"data="+p(t(h).replace(sb,""));return X(a,!1,{async:!0})};bc=function(){var a;a=(new Date).getTime()-Ja;h.pub=r;h.pag=z.href;h.uc=y;h.tz=x;h.slc=J;h.swc="undefined"!==typeof sw_handlers&&null!==sw_handlers?sw_handlers:0;h.ulc=0;h.jsl=a;h.guid=n;h.slmcid=L;h.uuid=E;h.sessid=u;h.pref=M;h.phr={};h.unl={};a={data:t(h)};o&&(a.dnt=o);D&&(a.fdnt=1);a=ea(a);if(Q||!Ra("//t.skimresources.com/api/track.php",a,hb))return dc(),!0;null!=g.skimlinks_runner&&
(g.skimlinks_runner.tracking=1);return!0};var ec=new function(a){function b(a,c){e||1E3<c?"function"==typeof a&&(e?d?a(!0):a(!1):a(!1)):setTimeout(b,c*=2,a,c)}function c(){e||(g.complete&&h.complete&&(e=!0),e&&"0"!=g.width&&"0"==h.width&&(d=!0))}var d=!1,e=!1,g=null,h=null;this.detect=function(i){a:{try{var j=navigator.userAgent.toLowerCase();if(-1==j.indexOf("firefox")&&-1==j.indexOf("chrome")){e=!0;d=!1;break a}}catch(l){}j=11*Math.random();g=new Image;g.onload=c;g.src=a.replace(/\*/,1).replace(/\*/,
j);h=new Image;h.onload=c;h.src=a.replace(/\*/,2).replace(/\*/,j)}b(i,250)}}("//p.skimresources.com/px.gif?ch=*&rn=*");g.skimlinks_manual||Xa()})(this);
